trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionEndpoint: 'Zenith-APIM'
  apimServiceName: 'linda'
  resourceGroupName: 'ochemMachine'
  apiSpecPath: 'path/to/edustipend.json' # Adjust the path to your Swagger file

jobs:
- job: DeployToAPIM
  displayName: 'Deploy to Azure API Management'
  steps:
  - task: UseNode@2
    inputs:
      versionSpec: '14.x'
      checkLatest: true

  - script: |
      npm install
      # Add additional commands here for building or preparing your Node.js API

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscriptionEndpoint)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az extension add --name azure-cli-iot-ext
        az apim api import --service $(apimServiceName) --resource-group $(resourceGroupName) --path $(apiSpecPath)
    displayName: 'Deploy API to APIM'
